n1 = float(input('Primeira nota do aluno: '))
n2 = float(input('Segunda nota do aluno: '))
n3 = float(input('Terceira nota do aluno: '))
mA = float((n1+n2+n3)/3)
print('Somando {}, {} e {}, concluiu-se que a média anual desse aluno é {:.1f}'.format(n1, n2, n3, mA))
